### ISSUE TITLE
Crash by NullReferenceException

### ISSUE THREAD

**Issue by cdhunt** [cdhunt/newrelic_perfmon_plugin#1]
Application: newrelic_perfmon_plugin.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException
Stack:
   at NewRelic.Platform.Sdk.Runner.SetupAndRun()
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart()

**Comment by Fydon** [comment]
I was getting a null pointer exception at [line 245][1]. I've [created a pull request][2] to hopefully fix the problem.

[1]: https://github.com/newrelic-platform/newrelic_dotnet_sdk/blob/master/NewRelic.Platform.Sdk/Binding/Context.cs#L245
[2]: https://github.com/newrelic-platform/newrelic_dotnet_sdk/pull/30
